AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to start EC2 instance and install on it the confluent platform and link a proper security group which allow all connections"
# Parameters:
#   ParamEC2:
#     Type: String
Resources:
  UpScalingPolicy:
    Type: "AWS::AutoScaling::ScalingPolicy"
    Properties:
      AdjustmentType: "ChangeInCapacity"
      AutoScalingGroupName: !Ref MyAutoScalingGroup
      Cooldown: "300"
      PolicyType: "SimpleScaling"
      ScalingAdjustment: '1'
  DownScalingPolicy:
    Type: "AWS::AutoScaling::ScalingPolicy"
    Properties:
      AdjustmentType: "ChangeInCapacity"
      AutoScalingGroupName: !Ref MyAutoScalingGroup
      Cooldown: "300"
      PolicyType: "SimpleScaling"
      ScalingAdjustment: '-1'
  CPUAlarmHigh:
     Type: "AWS::CloudWatch::Alarm"
     Properties:
        AlarmDescription: "Scale-up if CPU > 90% for 5 minutes"
        MetricName: "CPUUtilization"
        Namespace: "AWS/EC2"
        Statistic: "Average"
        Period: "300"
        EvaluationPeriods: "2"
        Threshold: "90"
        AlarmActions: [ Ref: UpScalingPolicy ]
        Dimensions:
        -
          Name: "AutoScalingGroupName"
          Value:
            Ref: MyAutoScalingGroup
        ComparisonOperator: "GreaterThanThreshold"
  CPUAlarmDown:
     Type: "AWS::CloudWatch::Alarm"
     Properties:
        AlarmDescription: "Scale-up if CPU < 70% for 5 minutes"
        MetricName: "CPUUtilization"
        Namespace: "AWS/EC2"
        Statistic: "Average"
        Period: "300"
        EvaluationPeriods: "2"
        Threshold: "90"
        AlarmActions: [ Ref: DownScalingPolicy ]
        Dimensions:
        -
          Name: "AutoScalingGroupName"
          Value:
            Ref: MyAutoScalingGroup
        ComparisonOperator: "LessThanThreshold"
  MyAutoScalingGroup:
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties:
      AvailabilityZones:
        Fn::GetAZs:
          Ref: "AWS::Region"
      MaxSize: 4
      MinSize: 1
      InstanceId: !Ref EC2Instance
      VPCZoneIdentifier:
      - subnet-4520f632
      - subnet-98633cde
      - subnet-76d87013
  EC2Instance:
      Type: "AWS::EC2::Instance"
      Properties:
        ImageId: "ami-162c2575"
        KeyName: "NIG-NPA-kafka-pilot"
        InstanceType: t2.large
        Tags:
         - Key: AutoStop
           Value: true
        SecurityGroupIds:
        - !Ref ConfluentSecurityGroup
        UserData:
          Fn::Base64: !Sub |     # No more Fn::Join needed
            #!/bin/bash
            sudo rpm --import http://packages.confluent.io/rpm/3.2/archive.key;

            sudo touch /etc/yum.repos.d/confluent.repo;
            sudo chmod 666 /etc/yum.repos.d/confluent.repo;
            sudo echo '[Confluent.dist]
            name=Confluent repository (dist)
            baseurl=http://packages.confluent.io/rpm/3.2/6
            gpgcheck=1
            gpgkey=http://packages.confluent.io/rpm/3.2/archive.key
            enabled=1

            [Confluent]
            name=Confluent repository
            baseurl=http://packages.confluent.io/rpm/3.2
            gpgcheck=1
            gpgkey=http://packages.confluent.io/rpm/3.2/archive.key
            enabled=1' > /etc/yum.repos.d/confluent.repo;

            sudo yum clean all;
            sudo yum install confluent-platform-2.11;
      # Metadata:
      #   Comment1: "Download and install everything necessary to use and run the Confluent platform"
      #   AWS::CloudFormation::Init:
      #     config:
      #       files:
      #         testFile.txt:
      #           content: "test"
      #           mode: "000666"
      #           owner: "root"
      #           group: "root"
      #         /etc/yum.repos.d/confluent.repo:
      #           content: [
      #             "[Confluent.dist]",
      #             "name=Confluent repository (dist)",
      #             "baseurl=http://packages.confluent.io/rpm/3.2/6",
      #             "gpgcheck=1",
      #             "gpgkey=http://packages.confluent.io/rpm/3.2/archive.key",
      #             "enabled=1",
      #             "[Confluent]",
      #             "name=Confluent repository",
      #             "baseurl=http://packages.confluent.io/rpm/3.2",
      #             "gpgcheck=1",
      #             "gpgkey=http://packages.confluent.io/rpm/3.2/archive.key",
      #             "enabled=1"]
      #           mode: "000666"
      #           owner: "root"
      #           group: "root"
      #       packages:
      #         rpm:
      #           epel: "http://packages.confluent.io/rpm/3.2/archive.key"
      #         yum:
      #           confluent-platform-2.11: []
  ConfluentSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group opened to all ips for the hands-on duration"
      SecurityGroupEgress:
        - IpProtocol: '-1'
          FromPort: '0'
          ToPort: '0'
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '0'
          ToPort: '65535'
          CidrIp: 0.0.0.0/0
      VpcId: "vpc-4f7bad2a"
Outputs:
  PublicIp1:
    Value: !GetAtt EC2Instance.PublicIp
    Description: "Public ip of the set up EC2 Instance"
