AWSTemplateFormatVersion: "2010-09-09"
Description: "Template to start EC2 instance from image containing kafka and other tools with an EIP and a proper security group"
Resources:
  EC2Instance1:
      Type: "AWS::EC2::Instance"
      Properties:
          ImageId: "ami-4a6e6529"
          KeyName: "NIG-NPA-kafka-pilot"
          InstanceType: t2.small
          SecurityGroupIds:
          - !Ref HandsOnSecurityGroup
  EC2Instance2:
      Type: "AWS::EC2::Instance"
      Properties:
          ImageId: "ami-4a6e6529"
          KeyName: "NIG-NPA-kafka-pilot"
          InstanceType: t2.small
          SecurityGroupIds:
          - !Ref HandsOnSecurityGroup
  EC2Instance3:
      Type: "AWS::EC2::Instance"
      Properties:
          ImageId: "ami-4a6e6529"
          KeyName: "NIG-NPA-kafka-pilot"
          InstanceType: t2.small
          SecurityGroupIds:
          - !Ref HandsOnSecurityGroup
  EC2Instance4:
      Type: "AWS::EC2::Instance"
      Properties:
          ImageId: "ami-4a6e6529"
          KeyName: "NIG-NPA-kafka-pilot"
          InstanceType: t2.small
          SecurityGroupIds:
          - !Ref HandsOnSecurityGroup
  EC2Instance5:
      Type: "AWS::EC2::Instance"
      Properties:
          ImageId: "ami-4a6e6529"
          KeyName: "NIG-NPA-kafka-pilot"
          InstanceType: t2.small
          SecurityGroupIds:
          - !Ref HandsOnSecurityGroup
  EC2Instance6:
      Type: "AWS::EC2::Instance"
      Properties:
          ImageId: "ami-4a6e6529"
          KeyName: "NIG-NPA-kafka-pilot"
          InstanceType: t2.small
          SecurityGroupIds:
          - !Ref HandsOnSecurityGroup
  HandsOnSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group opened to all ips for the hands-on duration"
      SecurityGroupEgress:
        - IpProtocol: '-1'
          FromPort: '0'
          ToPort: '0'
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '0'
          ToPort: '65535'
          CidrIp: 0.0.0.0/0
      VpcId: "vpc-4f7bad2a"
Outputs:
  PublicIp1:
    Value: !GetAtt EC2Instance1.PublicIp
    Description: "Public ip of the set up EC2 Instance"
  PublicIp2:
    Value: !GetAtt EC2Instance2.PublicIp
    Description: "Public ip of the set up EC2 Instance"
  PublicIp3:
    Value: !GetAtt EC2Instance3.PublicIp
    Description: "Public ip of the set up EC2 Instance"
  PublicIp4:
    Value: !GetAtt EC2Instance4.PublicIp
    Description: "Public ip of the set up EC2 Instance"
  PublicIp5:
    Value: !GetAtt EC2Instance5.PublicIp
    Description: "Public ip of the set up EC2 Instance"
  PublicIp6:
    Value: !GetAtt EC2Instance6.PublicIp
    Description: "Public ip of the set up EC2 Instance"
